---
title: STAT 477 HW2
author: Charles Yang
date: 1/27/2022
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(results = "hide")
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Problem 3
### 3a
```{r}
x <- rep(0, 60)
x[1:3] <- 1
cockerspaniels <- data.frame(anemic = x)

cockerspaniels$anemic <- as.factor(cockerspaniels$anemic)
counts <- cockerspaniels %>%
    group_by(anemic) %>%
    summarise(count = n())

rel <- counts$count / sum(counts$count)
counts <- cbind(counts, rel)

ggplot(counts, aes(x = anemic, y = count)) +
    geom_bar(stat = "identity") +
    labs(title = "Cocker Spaniel Breeding",
         x = "Is Anemic",
         y = "Count")

counts
```

### 3c
```{r}
n <- 60
p <- 0.3
proby <- dbinom(0:n, n, p)
proby[17:n] %>% sum
```

### 3d
```{r}
proby[1:11] %>% sum
```

### 3e
```{r}
.3*60
```

### 3d
```{r}
60*0.3*0.7
```

### 3g
```{r}
# probability distribution of proby
y <- c(0:n)

bars <- data.frame(y, proby)

ggplot(bars, aes(x = y, y = proby)) + 
    geom_bar(stat="identity", width = 1, fill = "blue", 
             colour = "black") +
    theme_bw() +
    theme(axis.title.y = element_text(size = rel(1.4)),
          axis.title.x = element_text(size = rel(1.4)),
          axis.text.x = element_text(size = rel(1.6)),
          axis.text.y = element_text(size = rel(1.6)),
          plot.title = element_text(hjust=0.5, size = rel(2))) +
    labs(x = "Number of Anermic Cocker Spaniels",
         y = "Probability",
         title = "Binomial Distribution")
```

The probability distribution appears to be roughly normal.