---
title: "hw8"
author: "Charles Yang"
date: "11/7/2021"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(results="hide")
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(caret)
library(class)
library(glmnet)
library(MASS)
library(foreign)
library(nnet)
```
```{r, echo=FALSE}
load_mnist <- function() {
  load_image_file <- function(filename) {
    ret = list()
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    ret$n = readBin(f,'integer',n=1,size=4,endian='big')
    nrow = readBin(f,'integer',n=1,size=4,endian='big')
    ncol = readBin(f,'integer',n=1,size=4,endian='big')
    x = readBin(f,'integer',n=ret$n*nrow*ncol,size=1,signed=F)
    ret$x = matrix(x, ncol=nrow*ncol, byrow=T)
    close(f)
    ret
  }
  load_label_file <- function(filename) {
    f = file(filename,'rb')
    readBin(f,'integer',n=1,size=4,endian='big')
    n = readBin(f,'integer',n=1,size=4,endian='big')
    y = readBin(f,'integer',n=n,size=1,signed=F)
    close(f)
    y
  }
  train <<- load_image_file('train-images-idx3-ubyte')
  test <<- load_image_file('t10k-images-idx3-ubyte')
  
  train$y <<- load_label_file('train-labels-idx1-ubyte')
  test$y <<- load_label_file('t10k-labels-idx1-ubyte')  
  
  return(
    list(
      train = train,
      test = test
    )
  )
}


show_digit <- function(arr784, col=gray(12:1/12), ...) {
  image(matrix(arr784, nrow=28)[,28:1], col=col, ...)
}
```

<style type="text/css">
@import url("https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css");
</style>

```{r}
setwd("C:/Users/15155/Desktop/ds303/hw8/mnist")
train <- NULL
test <- NULL
load_mnist()
```
```{r}
numberTrainIndex = sample(1:train$n, 3000)
numberTestIndex = sample(1:test$n, 100)

numberTrainX = train$x[numberTrainIndex, ]
numberTrainY = train$y[numberTrainIndex]
numberTestX = test$x[numberTestIndex, ]
numberTestY = test$y[numberTestIndex]
```
```{r}
K = c(1, 5, 7, 9)
flds <- createFolds(numberTrainY, k = 10, list = TRUE, returnTrain = FALSE)

cvMisclassification = matrix(NA, 10, 4)

for(j in 1:4){
  k = K[j]
  for(i in 1:10){
    test_index = flds[[i]]
    
    testX = numberTrainX[test_index, ]
    trainX = numberTrainX[-test_index, ]
  
    testY = numberTrainY[test_index]
    trainY = numberTrainY[-test_index]
    
    knn.pred = knn(trainX, testX, trainY, k=k)
    cvMisclassification[i,j] = mean(testY != knn.pred)
  }
}
```
```{r results="show"}
bestK = which.min(apply(cvMisclassification,2,mean))

train.X = numberTrainX
train.Y = numberTrainY
test.X = numberTestX
knn.pred = knn(train.X, test.X, train.Y, k=K[bestK])

print(paste0("Best K: ", K[bestK]))
table(knn.pred, numberTestY)
mean(numberTestY == knn.pred)
mean(numberTestY != knn.pred)
```
```{r error=TRUE}
numberTrainDF <- data.frame(cbind(numberTrainX, numberTrainY))

lda.fit = lda(numberTrainY~., data=numberTrainDF)
```
```{r error=TRUE}
multinom(numberTrainY~., data=numberTrainDF)
```

```{=html}
<section class="section">
<div class="card">
  <header class="card-header">
    <p class="card-header-title">
      
      1. Number Classifier
      
    </p>
  </header>
  
  <div class="card-content">
    <div class="content">
     
      a. 10 fold cross validation for KNN gives us the best k of 1. We get a misclassification rate of 0.08. See output above for confusion matrix. Values may vary due to lack of seed.
     
    </div>
  </div>
  
  <div class="card-content">
    <div class="content">
     
      b. We get that some variables are constant. This means that the covariance matrix was singular, making it impossible to compute the inverse.
     
    </div>
  </div>
  
  <div class="card-content">
    <div class="content">
     
      c. We get an error saying that there's too many weights.
     
    </div>
  </div>
  
  <div class="card-content">
    <div class="content">

      d. This dataset has a few problems: The covariance matrices are completely useless to other methods of classification. This is not a problem for KNN. Additionally, we have a large amount of data, for which KNN performs will with.
     
    </div>
  </div>
  
</div>
</section>

<hr/>
```

```{r}
setwd("C:/Users/15155/Desktop/ds303/hw8/fashion-mnist")
train <- NULL
test <- NULL
load_mnist()
```

```{r}
show_digit(train$x[1, ])
show_digit(train$x[2, ])
show_digit(train$x[3, ])
show_digit(train$x[4, ])
show_digit(train$x[5, ])
```


```{r}
numberTrainIndex = sample(1:train$n, 3000)
numberTestIndex = sample(1:test$n, 100)

numberTrainX = train$x[numberTrainIndex, ]
numberTrainY = train$y[numberTrainIndex]
numberTestX = test$x[numberTestIndex, ]
numberTestY = test$y[numberTestIndex]
```
```{r}
K = c(1, 5, 7, 9)
flds <- createFolds(numberTrainY, k = 10, list = TRUE, returnTrain = FALSE)

cvMisclassification = matrix(NA, 10, 4)

for(j in 1:4){
  k = K[j]
  for(i in 1:10){
    test_index = flds[[i]]
    
    testX = numberTrainX[test_index, ]
    trainX = numberTrainX[-test_index, ]
  
    testY = numberTrainY[test_index]
    trainY = numberTrainY[-test_index]
    
    knn.pred = knn(trainX, testX, trainY, k=k)
    cvMisclassification[i,j] = mean(testY != knn.pred)
  }
}
```
```{r results="show"}
bestK = which.min(apply(cvMisclassification,2,mean))

train.X = numberTrainX
train.Y = numberTrainY
test.X = numberTestX
knn.pred = knn(train.X, test.X, train.Y, k=K[bestK])

print(paste0("Best K: ", K[bestK]))
table(knn.pred, numberTestY)
mean(numberTestY == knn.pred)
mean(numberTestY != knn.pred)
```
```{=html}
<section class="section">
<div class="card">
  <header class="card-header">
    <p class="card-header-title">
      
      2. Fashion Classifier
      
    </p>
  </header>
  
  <div class="card-content">
    <div class="content">
     
      a. Man, I can barely make out the first 2 items. They are a shoe and a t-shirt. IDK about the rest. The fourth might be a dress? Super blurry.
     
    </div>
  </div>
  
  <div class="card-content">
    <div class="content">
     
      b. THe misclassification rate for the fashion dataset is 0.14, which is nearly double that of the number classifier. Understandably so. Values may vary due to lack of seed.
     
    </div>
  </div>
  
</div>
</section>

<hr/>
```
