---
title: "multiple_linear_regression"
author: "Charles Yang"
date: "8/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

```{r}
# read in patient.txt
patient = read.table("C:/users/15155/desktop/ds303/multiple_linear_regression/patient.txt", header=FALSE)

# give each column its variable name
names(patient) = c("satisf","age","severe","anxiety")

head(patient)
str(patient)
pairs(patient) #pairwise scatterplot

# What is the response vector? 
Y = patient$satisf

# number of observations in the data set
n = dim(patient)[1]
```

```{r}
# construct our design matrix 
# first column needs to be column of 1's

X = cbind(rep(1,n),patient$age, patient$severe, patient$anxiety) 

# least square estimators (big beta hat B = (X^T * X)^-1 * X^T * Y)
XtX = t(X)%*%X
b = solve(XtX)%*%t(X)%*%Y

# What is my predicted value for Y? 

Yhat = X%*%b
```

```{r}
# use the lm function 
model=lm(satisf~age+severe+anxiety,data=patient)
summary(model)
names(model)

#########################################################
## MSE? ################################################
## divide our data into a training set and a test set
set.seed(10)
train_index = sample(1:n,n/2,rep=FALSE)

train_patients = patient[train_index,]
test_patients = patient[-train_index,]

model_train = lm(satisf~age+severe+anxiety,data=train_patients)

predicted_values = predict(model_train,test_patients)
MSE_test = mean((test_patients$satisf - predicted_values)^2)
```

```{r}
#########################################################
####### Properties of our linear regression model #######
#########################################################

## let's simulate data where we know the true population regresssion line

## suppose we have 1 single predictor (X1)
n = 100
beta_0 = ?
beta_1 = ?
X1 = seq(0,10, length.out=n)

# generate Y based on true population regression line


```

